### ISSUE TITLE
Error during deploy: "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by lextoumbourou** [EngineerBetter/control-tower#44]
Hi team,

Trying to perform a deploy using the following command:

```
AWS_ACCESS_KEY_ID=<redacted>  \
AWS_SECRET_ACCESS_KEY=<redacted> \
./control-tower-darwin-amd64 deploy --iaas aws --region ap-southeast-2 ci-test
```

I am receiving this error after the deploy starts

```
Started deploying
  Waiting for the agent on VM '<redacted>'... Finished (00:00:00)
  Stopping jobs on instance 'unknown/0'... Finished (00:00:00)
  Unmounting disk 'vol-<redacted>'... Finished (00:00:05)
  Deleting VM '<redacted>'... Finished (00:00:34)
  Creating VM for instance 'bosh/0' from stemcell 'ami-<redacted> light'... Finished (00:00:40)
  Waiting for the agent on VM 'i-<redacted>' to be ready... Finished (00:00:31)
  Attaching disk 'vol-<redacted>' to VM 'i-<redacted>'... Finished (00:00:22)
  Rendering job templates... Finished (00:00:09)
  Compiling package 'ruby-2.4-r5/726cbb2214e138b576700db6a30698edb2b994e2'... Skipped [Package already compiled] (00:00:16)
  Compiling package 'bpm-runc/c0b41921c5063378870a7c8867c6dc1aa84e7d85'... Skipped [Package already compiled] (00:00:16)
  Compiling package 'golang/27413c6b5a88ea20a24a9eed74d4b090b7b88331'...

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x106b4f3]

goroutine 629 [running]:
io.copyBuffer(0x1bfdd00, 0xc420446210, 0x0, 0x0, 0xc4205a2000, 0x8000, 0x8000, 0xc420446210, 0xc420446210, 0x19cb9c0)
	/usr/local/go/src/io/io.go:400 +0x143
io.Copy(0x1bfdd00, 0xc420446210, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:362 +0x5a
net.genericReadFrom(0x1bfc140, 0xc42000c090, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:597 +0x84
net.(*TCPConn).readFrom(0xc42000c090, 0x0, 0x0, 0xc420598e08, 0x100e04d, 0x1998080)
	/usr/local/go/src/net/tcpsock_posix.go:51 +0x4d
net.(*TCPConn).ReadFrom(0xc42000c090, 0x0, 0x0, 0x240ac10, 0xc42000c090, 0xc42001c001)
	/usr/local/go/src/net/tcpsock.go:103 +0x5f
io.copyBuffer(0x1bfc140, 0xc42000c090, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1a9ff80, 0x0, 0x1bfc140)
	/usr/local/go/src/io/io.go:386 +0x31a
io.Copy(0x1bfc140, 0xc42000c090, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:362 +0x5a
github.com/cloudfoundry/bosh-cli/deployment/sshtunnel.(*sshTunnel).Start.func3(0x1c0bfa0, 0xc42000c090, 0x0, 0x0, 0xc4203989b0, 0xc420354480)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/deployment/sshtunnel/ssh_tunnel.go:85 +0xc3
created by github.com/cloudfoundry/bosh-cli/deployment/sshtunnel.(*sshTunnel).Start
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/deployment/sshtunnel/ssh_tunnel.go:84 +0x314
```

I am running version 0.8.2 of Control Tower:

```
./control-tower-darwin-amd64 --version
Control-Tower version 0.8.2
```

and bosh-cli version 6.1.0-9:

```
bosh --version
version 6.1.0-9c1c210c-2019-09-18T17:33:48Z

Succeeded
```

Any ideas about how to troubleshoot it?

**Comment by aranair** [comment]
Hit this as well
