### ISSUE TITLE
Deployment on AWS fails on ruby2.4 compilation

### ISSUE THREAD

**Issue by odedia** [EngineerBetter/control-tower#5]
While running installation, I am failing on ruby2.4 compilation.

I am using Control Tower 0.3.1.

```
AWS_ACCESS_KEY_ID=<key> \
AWS_SECRET_ACCESS_KEY=<secret> \
control-tower deploy \
    --region eu-west-2 \
    --iaas aws \
    --workers 3 \
    ${PCF_SUBDOMAIN_NAME}
```

This is the output (streamed from BOSH it appears):
```
Started validating
  Downloading release 'bosh'... Finished (00:00:19)
  Validating release 'bosh'... Finished (00:00:01)
  Downloading release 'bpm'... Finished (00:00:23)
  Validating release 'bpm'... Finished (00:00:01)
  Downloading release 'bosh-aws-cpi'... Finished (00:00:01)
  Validating release 'bosh-aws-cpi'... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Finished (00:00:01)
  Validating stemcell... Finished (00:00:00)
Finished validating (00:00:49)

Started installing CPI
  Compiling package 'ruby-2.4-r4/0cdc60ed7fdb326e605479e9275346200af30a25'... Failed (00:01:45)
Failed installing CPI (00:01:45)

Installing CPI:
  Compiling job package dependencies for installation:
    Compiling job package dependencies:
      Compiling package:
        Running command: 'bash -x packaging', stdout: 'checking for a BSD-compatible install... /usr/bin/install -c
...
...
...
+ make install
+ tar xzf ruby-2.4.4.tar.gz
+ set -e
+ cd ruby-2.4.4
++ uname -m
+ '[' x86_64 == ppc64le ']'
+ LDFLAGS='-Wl,-rpath -Wl,/home/ubuntu/.bosh/installations/30180f1d-f2c0-43ec-5256-2500ad164e98/packages/ruby-2.4-r4'
+ CFLAGS=-fPIC
+ ./configure --prefix=/home/ubuntu/.bosh/installations/30180f1d-f2c0-43ec-5256-2500ad164e98/packages/ruby-2.4-r4 --disable-install-doc --with-opt-dir=/usr/local/opt/openssl:/home/ubuntu/.bosh/installations/30180f1d-f2c0-43ec-5256-2500ad164e98/packages/ruby-2.4-r4 --without-gmp
+ make
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
+ make install
+ mkdir /home/ubuntu/.bosh/installations/30180f1d-f2c0-43ec-5256-2500ad164e98/packages/ruby-2.4-r4/bosh
+ cp gemrc /home/ubuntu/.bosh/installations/30180f1d-f2c0-43ec-5256-2500ad164e98/packages/ruby-2.4-r4/bosh/gemrc
+ cp compile.env /home/ubuntu/.bosh/installations/30180f1d-f2c0-43ec-5256-2500ad164e98/packages/ruby-2.4-r4/bosh/compile.env
+ cp runtime.env /home/ubuntu/.bosh/installations/30180f1d-f2c0-43ec-5256-2500ad164e98/packages/ruby-2.4-r4/bosh/runtime.env
+ source /home/ubuntu/.bosh/installations/30180f1d-f2c0-43ec-5256-2500ad164e98/packages/ruby-2.4-r4/bosh/runtime.env
++ export PATH=/home/ubuntu/.bosh/installations/30180f1d-f2c0-43ec-5256-2500ad164e98/packages/ruby-2.4-r4/bin:/usr/local/bin:/usr/bin:/bin
++ PATH=/home/ubuntu/.bosh/installations/30180f1d-f2c0-43ec-5256-2500ad164e98/packages/ruby-2.4-r4/bin:/usr/local/bin:/usr/bin:/bin
++ export GEMRC=/home/ubuntu/.bosh/installations/30180f1d-f2c0-43ec-5256-2500ad164e98/packages/ruby-2.4-r4/bosh/gemrc
++ GEMRC=/home/ubuntu/.bosh/installations/30180f1d-f2c0-43ec-5256-2500ad164e98/packages/ruby-2.4-r4/bosh/gemrc
+ tar zxvf rubygems-2.7.6.tgz
+ set -e
+ cd rubygems-2.7.6
+ ruby setup.rb --no-ri --no-rdoc
/home/ubuntu/.bosh/installations/30180f1d-f2c0-43ec-5256-2500ad164e98/tmp/bosh-release-pkg246764010/rubygems-2.7.6/lib/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- zlib (LoadError)
	from /home/ubuntu/.bosh/installations/30180f1d-f2c0-43ec-5256-2500ad164e98/tmp/bosh-release-pkg246764010/rubygems-2.7.6/lib/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /home/ubuntu/.bosh/installations/30180f1d-f2c0-43ec-5256-2500ad164e98/tmp/bosh-release-pkg246764010/rubygems-2.7.6/lib/rubygems/package.rb:47:in `<top (required)>'
	from /home/ubuntu/.bosh/installations/30180f1d-f2c0-43ec-5256-2500ad164e98/tmp/bosh-release-pkg246764010/rubygems-2.7.6/lib/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /home/ubuntu/.bosh/installations/30180f1d-f2c0-43ec-5256-2500ad164e98/tmp/bosh-release-pkg246764010/rubygems-2.7.6/lib/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /home/ubuntu/.bosh/installations/30180f1d-f2c0-43ec-5256-2500ad164e98/tmp/bosh-release-pkg246764010/rubygems-2.7.6/lib/rubygems/commands/pristine_command.rb:3:in `<top (required)>'
	from /home/ubuntu/.bosh/installations/30180f1d-f2c0-43ec-5256-2500ad164e98/tmp/bosh-release-pkg246764010/rubygems-2.7.6/lib/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /home/ubuntu/.bosh/installations/30180f1d-f2c0-43ec-5256-2500ad164e98/tmp/bosh-release-pkg246764010/rubygems-2.7.6/lib/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /home/ubuntu/.bosh/installations/30180f1d-f2c0-43ec-5256-2500ad164e98/tmp/bosh-release-pkg246764010/rubygems-2.7.6/lib/rubygems/commands/setup_command.rb:583:in `regenerate_binstubs'
	from /home/ubuntu/.bosh/installations/30180f1d-f2c0-43ec-5256-2500ad164e98/tmp/bosh-release-pkg246764010/rubygems-2.7.6/lib/rubygems/commands/setup_command.rb:155:in `execute'
	from /home/ubuntu/.bosh/installations/30180f1d-f2c0-43ec-5256-2500ad164e98/tmp/bosh-release-pkg246764010/rubygems-2.7.6/lib/rubygems/command.rb:313:in `invoke_with_build_args'
	from /home/ubuntu/.bosh/installations/30180f1d-f2c0-43ec-5256-2500ad164e98/tmp/bosh-release-pkg246764010/rubygems-2.7.6/lib/rubygems/command_manager.rb:171:in `process_args'
	from /home/ubuntu/.bosh/installations/30180f1d-f2c0-43ec-5256-2500ad164e98/tmp/bosh-release-pkg246764010/rubygems-2.7.6/lib/rubygems/command_manager.rb:141:in `run'
	from /home/ubuntu/.bosh/installations/30180f1d-f2c0-43ec-5256-2500ad164e98/tmp/bosh-release-pkg246764010/rubygems-2.7.6/lib/rubygems/gem_runner.rb:59:in `run'
	from setup.rb:46:in `<main>'
+ echo 'Cannot install rubygems'
+ exit 1
':
          exit status 1

Exit code 1
```

**Comment by crsimmons** [comment]
Hi @odedia,

This looks like it errored on the director deploy which implies the failed compilation happened on whichever machine you ran `control-tower deploy` from. What OS are you deploying from?

I've seen similar errors pop up when the [bosh-cli prerequisite dependencies](https://bosh.io/docs/cli-v2-install/#additional-dependencies) are not present in the environment.

**Comment by odedia** [comment]
Hi @crsimmons , I'm deploying from an EC2 VM on AWS, running Ubuntu 18.04.
I'm surprised BOSH compilation would occur on the client side? It should be done from the remote bosh director, no?

**Comment by odedia** [comment]
Thank you.

I used the standard documentation to install ruby 2.4 before running and it now continues with the installation.

https://gorails.com/setup/ubuntu/18.04

```
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

sudo apt-get update
sudo apt-get install git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev software-properties-common libffi-dev nodejs yarn
```
